name: Generate with zas

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
      - name: Setup Pages
        uses: actions/configure-pages@d5606572c479bee637007364c6b4800ac4fc8573
      - name: Install ZAS
        run: go install github.com/darccio/zas/cmd/zas@025861715cd4cd56ffa39bb961cb3bffe586a716
      - name: Upload artifact
        uses: actions/upload-pages-artifact@2d163be3ddce01512f3eea7ac5b7023b5d643ce1
        with:
          path: '.zas/deploy/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@854d7aa1b99e4509c4d1b53d69b7ba4eaf39215a
